#include <stdlib.h>
#include <cstdlib>
#include <cstdint>
#include <algorithm>
#include <iostream>
#include <filesystem>
#include <fstream>
#include <vector>
#include <optional>
#include <ctime>
#include <chrono>
#include <queue>
#include <random>
#include <functional>
#include <unordered_map>
#include <string>
#include <sstream>

#include <SDL2/SDL.h>
#include <SDL2/SDL_image.h>